import {KEY,loadRecords,changeRecord} from './storage.mjs';
const app=document.querySelector('#app'),status=document.querySelector('#status');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());
let records=[],editing=null,month=today().slice(0,7),query='',busy=false;
function notice(message=''){status.textContent=message;}
function render(){app.removeAttribute('aria-busy');app.innerHTML=`<div class="intro"><div><h1>業務記録</h1><p class="muted">日々の仕事と気づきを残す、あなた専用の記録。</p><small>試作版 · ログイン不要</small></div><button id="export">記録を書き出す</button></div><div class="layout"><section><h2 id="form-title">記録を追加</h2><form id="record-form"><label>日付<input name="work_date" type="date" required value="${today()}"></label><label>業務名<input name="title" required maxlength="160" placeholder="例：田中邸の図面確認"></label><label>作業時間（分）<input name="minutes" type="number" min="0" max="1440" step="1" required value="0"></label><label>内容・気づき<textarea name="body" maxlength="10000" placeholder="取り組んだこと、結果、次にすること"></textarea></label><div class="actions"><button class="primary" type="submit">保存する</button><button id="cancel" type="button" hidden>編集をやめる</button></div></form><p class="muted">記録はこのブラウザ・端末に保存されます。同じブラウザを使う人は閲覧できます。ブラウザのデータを削除すると記録も消えます。定期的に書き出してください。</p></section><section><div class="filters"><label>表示する月<input id="month" type="month" value="${month}"></label><label>検索<input id="search" type="search" placeholder="業務名・内容" value="${esc(query)}"></label><button id="refresh">更新</button></div><p id="summary" class="muted"></p><div id="records"></div></section></div>`;
app.querySelector('#export').onclick=()=>{try{const blob=new Blob([JSON.stringify(loadRecords(localStorage),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='業務記録-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('記録を書き出しました。');}catch(err){notice(err.message);}};
app.querySelector('#month').oninput=e=>{month=e.target.value;list();};app.querySelector('#search').oninput=e=>{query=e.target.value;list();};app.querySelector('#refresh').onclick=async()=>{try{await load();notice('最新の記録を取得しました。');}catch(err){notice(err.message);}};
app.querySelector('#cancel').onclick=reset;app.querySelector('#record-form').onsubmit=save;list();}
function reset(){editing=null;const f=app.querySelector('#record-form');f.reset();f.elements.work_date.value=today();app.querySelector('#form-title').textContent='記録を追加';app.querySelector('#cancel').hidden=true;}
function list(){const filtered=records.filter(r=>(!month||r.work_date.startsWith(month))&&`${r.title} ${r.body}`.normalize('NFKC').toLowerCase().includes(query.normalize('NFKC').trim().toLowerCase())).sort((a,b)=>b.work_date.localeCompare(a.work_date)||b.updated_at.localeCompare(a.updated_at));app.querySelector('#summary').textContent=`${filtered.length}件 · 作業時間 ${filtered.reduce((sum,r)=>sum+r.minutes,0)}分`;const el=app.querySelector('#records');el.innerHTML=filtered.length?filtered.map(r=>`<div class="record"><small>${esc(r.work_date)} · ${r.minutes}分</small><h3>${esc(r.title)}</h3><p>${esc(r.body)}</p><div class="actions"><button data-edit="${r.id}">編集</button><button data-delete="${r.id}">削除</button></div></div>`).join(''):'<p class="muted">該当する記録はありません。</p>';el.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{if(busy)return;const r=records.find(r=>r.id===b.dataset.edit);editing={...r};const f=app.querySelector('#record-form');for(const k of ['work_date','title','body','minutes'])f.elements[k].value=r[k];app.querySelector('#form-title').textContent='記録を編集';app.querySelector('#cancel').hidden=false;f.elements.title.focus();});el.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(busy)return;const r=records.find(r=>r.id===b.dataset.delete);if(!confirm(`「${r.title}」を削除しますか？`))return;busy=true;b.disabled=true;try{records=changeRecord(localStorage,'delete',{id:r.id,version:r.version});if(editing?.id===r.id)reset();list();notice('削除しました。');}catch(err){notice(err.message);b.disabled=false;}finally{busy=false;}});}
async function save(e){e.preventDefault();if(busy)return;const f=e.target,payload=Object.fromEntries(new FormData(f));payload.title=payload.title.trim();if(!payload.title){notice('業務名を入力してください。');return;}payload.minutes=Number(payload.minutes);payload.id=editing?.id||crypto.randomUUID();if(editing)payload.version=editing.version;busy=true;const b=f.querySelector('[type=submit]');b.disabled=true;try{records=changeRecord(localStorage,editing?'update':'create',payload);month=payload.work_date.slice(0,7);query='';app.querySelector('#month').value=month;app.querySelector('#search').value='';reset();list();notice('保存しました。');}catch(err){notice(err.message);}finally{busy=false;b.disabled=false;}}
async function load(){records=loadRecords(localStorage);list();}
function boot(){try{records=loadRecords(localStorage);render();}catch(err){app.removeAttribute('aria-busy');app.innerHTML='<section><h1>保存データを読み込めません</h1><p>ブラウザの保存機能と空き容量を確認してください。既存の記録は上書きしていません。</p><button id=retry>再試行</button></section>';app.querySelector('#retry').onclick=boot;notice(err.message);}}
window.addEventListener('storage',e=>{if(e.key===KEY){try{if(app.querySelector('#records'))load();else boot();notice('別の画面の変更を反映しました。');}catch(err){notice(err.message);}}});
window.addEventListener('beforeunload',e=>{const f=app.querySelector('#record-form');if(f&&(f.elements.title.value||f.elements.body.value)){e.preventDefault();e.returnValue='';}});
boot();
